from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

from fastapi import HTTPException, UploadFile, status

from app.core.config import get_settings
from app.schemas.cookies import CookiesStatus

MAX_COOKIES_BYTES = 1 * 1024 * 1024
NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# Generated by ModeloIA\n\n"
)


def _cookies_path() -> Path:
    return Path(get_settings().temp_dir) / "cookies.txt"


def _write_netscape_cookies(rows: Iterable[dict]) -> CookiesStatus:
    """Write cookies to the standard Netscape file used by yt-dlp.

    Each row must contain: domain, path, secure, expires, name, value.
    `expires` should be an int (epoch seconds) or 0 for session cookies.
    """
    lines: list[str] = []
    for row in rows:
        domain = str(row.get("domain") or "").strip()
        if not domain:
            continue
        host_only = not domain.startswith(".")
        flag = "FALSE" if host_only else "TRUE"
        path = str(row.get("path") or "/").strip() or "/"
        secure = "TRUE" if row.get("secure") else "FALSE"
        try:
            expires = int(row.get("expires") or 0)
        except (TypeError, ValueError):
            expires = 0
        if expires < 0:
            expires = 0
        name = str(row.get("name") or "").replace("\t", " ").replace("\n", " ")
        value = str(row.get("value") or "").replace("\t", " ").replace("\n", " ")
        if not name:
            continue
        lines.append("\t".join([domain, flag, path, secure, str(expires), name, value]))

    target = _cookies_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(NETSCAPE_HEADER + "\n".join(lines) + "\n", encoding="utf-8")
    return read_cookies_status()


def _is_netscape_cookie_file(text: str) -> bool:
    head = text.lstrip()[:200].lower()
    return "netscape http cookie file" in head or "http cookie file" in head


def read_cookies_status() -> CookiesStatus:
    path = _cookies_path()
    if not path.exists():
        return CookiesStatus(configured=False)

    try:
        raw = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return CookiesStatus(configured=False)

    domains = [
        line.split("\t", 1)[0].lstrip(".").lower()
        for line in raw.splitlines()
        if line and not line.startswith("#")
    ]
    has_instagram = any("instagram.com" in domain for domain in domains)
    has_youtube = any("youtube.com" in domain or "google.com" in domain for domain in domains)

    stat = path.stat()
    return CookiesStatus(
        configured=True,
        updated_at=datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc),
        size_bytes=stat.st_size,
        total_lines=len([line for line in raw.splitlines() if line and not line.startswith("#")]),
        has_instagram=has_instagram,
        has_youtube=has_youtube,
    )


def save_cookies_file(upload_file: UploadFile) -> CookiesStatus:
    if not upload_file.filename or not upload_file.filename.lower().endswith(".txt"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Envie um arquivo cookies.txt no formato Netscape.",
        )

    raw_bytes = upload_file.file.read(MAX_COOKIES_BYTES + 1)
    if len(raw_bytes) > MAX_COOKIES_BYTES:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail="Arquivo de cookies muito grande (limite de 1 MB).",
        )
    if not raw_bytes:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Arquivo de cookies vazio.",
        )

    text = raw_bytes.decode("utf-8", errors="ignore")
    if not _is_netscape_cookie_file(text):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Formato invalido. Exporte os cookies em formato Netscape (cookies.txt).",
        )

    target = _cookies_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(raw_bytes)
    return read_cookies_status()


def delete_cookies_file() -> CookiesStatus:
    path = _cookies_path()
    if path.exists():
        path.unlink()
    return read_cookies_status()
